models_config:
  Qwen2-0.5B-Instruct:
      model_path: /home/models/Qwen/Qwen2-0.5B-Instruct
  Qwen2-1.5B-Instruct:
      model_path: /home/models/Qwen/Qwen2-1.5B-Instruct
  Qwen2-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-7B-Instruct
  Qwen2-57B-A14B-Instruct-GPTQ-Int4:
      model_path: /home/models/Qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4
  Qwen2-Audio-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-Audio-7B-Instruct
  Qwen2-VL-2B-Instruct:
      model_path: /home/models/Qwen/Qwen2-VL-2B-Instruct
  Qwen2-VL-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-VL-7B-Instruct
  Qwen2.5-0.5B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-0.5B-Instruct
  Qwen2.5-1.5B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-1.5B-Instruct
  Qwen2.5-3B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-3B-Instruct
  Qwen2.5-7B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-7B-Instruct
  Qwen2.5-14B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-14B-Instruct
  Qwen2.5-32B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-32B-Instruct
  Qwen2.5-72B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-72B-Instruct
  Qwen2.5-Coder-1.5B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-Coder-1.5B-Instruct
  Qwen2.5-Coder-7B-Instruct:
    model_path: /home/models/Qwen/Qwen2.5-Coder-7B-Instruct
  glm-4-9b-chat:
      model_path: /home/models/THUDM/glm-4-9b-chat
  glm-4-9b-chat-1m:
      model_path: /home/models/THUDM/glm-4-9b-chat-1m
  glm-4v-9b:
      model_path: /home/models/THUDM/glm-4v-9b
  LongWriter-glm4-9b:
    model_path: /home/models/THUDM/LongWriter-glm4-9b
  LongWriter-llama3.1-8b:
    model_path: /home/models/THUDM/LongWriter-llama3.1-8b
  LongCite-llama3.1-8b:
    model_path: /home/models/THUDM/LongCite-llama3.1-8b
  LongCite-glm4-9b:
    model_path: /home/models/THUDM/LongCite-glm4-9b
  codegeex4-all-9b:
      model_path: /home/models/THUDM/codegeex4-all-9b
  MiniCPM-V-2_6:
      model_path: /home/models/openbmb/MiniCPM-V-2_6
  MiniCPM3-4B:
      model_path: /home/models/openbmb/MiniCPM3-4B
  DeepSeek-V2-Lite-Chat:
      model_path: /home/models/deepseek-ai/DeepSeek-V2-Lite-Chat
  DeepSeek-Coder-V2-Lite-Instruct:
      model_path: /home/models/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
  GOT-OCR2_0:
    model_path: /home/models/stepfun-ai/GOT-OCR2_0
  Kolors-diffusers:
      model_path: /home/models/Kwai-Kolors/Kolors-diffusers
  Kolors-image2image:
      model_path: /home/models/Kwai-Kolors/Kolors-diffusers
  FLUX.1-dev:
      model_path: /home/models/black-forest-labs/FLUX.1-dev
  CosyVoice-300M-SFT:
      model_path: /home/models/FunAudioLLM/CosyVoice-300M-SFT
  bge-m3:
      model_path: /home/models/BAAI/bge-m3
  jina-embeddings-v3:
      model_path: /home/models/jinaai/jina-embeddings-v3