models_config:
  Qwen2-0.5B-Instruct:
      model_path: /home/models/Qwen/Qwen2-0.5B-Instruct
  Qwen2-1.5B-Instruct:
      model_path: /home/models/Qwen/Qwen2-1.5B-Instruct
  Qwen2-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-7B-Instruct
  Qwen2-57B-A14B-Instruct-GPTQ-Int4:
      model_path: /home/models/Qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4
  Qwen2-Audio-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-Audio-7B-Instruct
  glm-4-9b-chat:
      model_path: /home/models/THUDM/glm-4-9b-chat
  glm-4-9b-chat-1m:
      model_path: /home/models/THUDM/glm-4-9b-chat-1m
  glm-4v-9b:
      model_path: /home/models/THUDM/glm-4v-9b
  MiniCPM-V-2_6:
      model_path: /home/models/openbmb/MiniCPM-V-2_6
  Kolors-diffusers:
      model_path: /home/models/Kwai-Kolors/Kolors-diffusers
  kolors-image2image:
      model_path: /home/models/Kwai-Kolors/Kolors-diffusers
  FLUX.1-dev:
      model_path: /home/models/black-forest-labs/FLUX.1-dev
  CosyVoice-300M-SFT:
      model_path: /home/models/FunAudioLLM/CosyVoice-300M-SFT
  bge-m3:
      model_path: /home/models/BAAI/bge-m3
