models_config:
  Qwen2-0.5B-Instruct:
      model_path: /home/models/Qwen/Qwen2-0.5B-Instruct
      model_type: completion
      load_method: load_qwen2
      generate_method: Qwen205BInstructInferenceGenerateConfig
      max_memory:
        0: "2GB"
  Qwen2-1.5B-Instruct:
      model_path: /home/models/Qwen/Qwen2-1.5B-Instruct
      model_type: completion
      load_method: load_qwen2
      generate_method: Qwen215BInstructInferenceGenerateConfig
      max_memory:
        0: "4GB"
  Qwen2-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-7B-Instruct
      model_type: completion
      load_method: load_qwen2
      generate_method: Qwen2InstructInferenceGenerateConfig
      max_memory:
        0: "20GB"
  Qwen2-57B-A14B-Instruct-GPTQ-Int4:
      model_path: /home/models/Qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4
      model_type: completion
      load_method: load_qwen2
      generate_method: Qwen2InstructInferenceGenerateConfig
      max_memory:
        0: "30GB"
  Qwen2-Audio-7B-Instruct:
      model_path: /home/models/Qwen/Qwen2-Audio-7B-Instruct
      model_type: completion
      load_method: load_qwen2_audio
      generate_method: Qwen2Audio7BInstructInferenceGenerateConfig
      max_memory:
        0: "30GB"
  glm-4-9b-chat:
      model_path: /home/models/THUDM/glm-4-9b-chat
      model_type: completion
      load_method: load_glm4
      generate_method: GLM49BChatInferenceGenerateConfig
      max_memory:
        0: "30GB"
  glm-4-9b-chat-1m:
      model_path: /home/models/THUDM/glm-4-9b-chat-1m
      model_type: completion
      load_method: load_glm4
      generate_method: GLM49BChat1MInferenceGenerateConfig
      max_memory:
        0: "30GB"
  glm-4v-9b:
      model_path: /home/models/THUDM/glm-4v-9b
      model_type: completion
      load_method: load_glm4
      generate_method: GLM4V9BInferenceGenerateConfig
      max_memory:
        0: "32GB"
  MiniCPM-V-2_6:
      model_path: /home/models/openbmb/MiniCPM-V-2_6
      model_type: completion
      load_method: load_mini_cpm
      generate_method: MiniCPMInferenceGenerateConfig
      max_memory:
        0: "32GB"
  Kolors-diffusers:
      model_path: /home/models/Kwai-Kolors/Kolors-diffusers
      model_type: diffuser
      load_method: load_kolors_diffusers
      generate_method: KolorsImageGenerateConfig
      max_memory:
        0: "32GB"
  kolors-image2image:
      model_path: /home/models/Kwai-Kolors/Kolors-diffusers
      model_type: diffuser
      load_method: load_kolors_image2image
      generate_method: KolorsImage2ImageGenerateConfig
      max_memory:
        0: "32GB"
  FLUX.1-dev:
      model_path: /home/models/black-forest-labs/FLUX.1-dev
      model_type: diffuser
      load_method: load_flux_diffusers
      generate_method: FLUXImageGenerateConfig
      max_memory:
        0: "32GB"
  CosyVoice-300M-SFT:
      model_path: /home/models/FunAudioLLM/CosyVoice-300M-SFT
      model_type: audio
      load_method: load_cosy_voice
      generate_method: CosyVoiceGenerateConfig
      max_memory:
        0: "32GB"
  bge-m3:
      model_path: /home/models/BAAI/bge-m3
      model_type: embedding
      load_method: load_embedding
